### ISSUE TITLE
ImportError: cannot import name 'work' from 'work'

### ISSUE THREAD

**Issue by jpfleischer** [cybertraining-dsc/su21-reu-361#1]
We have been trying to troubleshoot the import work function but I am getting this issue

![issue](https://user-images.githubusercontent.com/70083705/122627900-96d70f80-d080-11eb-96a0-75ff56d994d6.PNG)

The error output from cell [17] which contains `from work import work` reads as follows
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-17-a765250276a0> in <module>
----> 1 from work import work

ImportError: cannot import name 'work' from 'work' (c:\Users\Sledgehammer\Desktop\reu\su21-reu-361\project\code\work.py)
```

The error output from the next cell, which contains `work.work("Hello World!")` reads as follows
```
AttributeError                            Traceback (most recent call last)
<ipython-input-16-61b971354ca6> in <module>
----> 1 work.work("Hello World!")

AttributeError: module 'work' has no attribute 'work'
```

Even with the new __init__.py (empty file) it still seems to be not working. Will troubleshoot and report findings here.

**Comment by laszewsk** [comment]
I can not read the screenshot. use ascii copy

**Comment by jpfleischer** [comment]
> 
> 
> I can not read the screenshot. use ascii copy

I have copied and pasted the output, please let me know if it is better now.

**Comment by laszewsk** [comment]
Works in commandline:

cd code

```
$ cd code
# python --version
Python 3.9.5
$ which python
/Users/username/ENV3/bin/python
$ python test1.py
hallo
```

**Comment by laszewsk** [comment]
works in pycharm
works on commandline
there were prg errors in the checked in code that I fixed

**Comment by jpfleischer** [comment]
> 
> 
> works in pycharm
> works on commandline
> there were prg errors in the checked in code that I fixed

Thank you, it works now.
