### ISSUE TITLE
Permission denied (publickey) in VSCode when trying to Push or Pull (on Windows 10)

### ISSUE THREAD

**Issue by jpfleischer** [cybertraining-dsc/su21-reu-361#2]
I experienced an error when trying to push or pull my su21-reu-361 repo, but got it to work again after following two tutorials: [this stackoverflow page](https://stackoverflow.com/questions/52113738/starting-ssh-agent-on-windows-10-fails-unable-to-start-ssh-agent-service-erro) and [this github page](https://github.com/microsoft/vscode/issues/42039).

Steps I followed (from first link):

1. Open Powershell as administrator (press Windows key, type Powershell, click Run as Administrator)
2. Ensure that the Status says Stopped when you type this code in Powershell and press enter: `Get-Service ssh-agent`
3. Check that the StartType says Disabled when you type this code in Powershell and press enter: `Get-Service ssh-agent | Select StartType`
4. Type this code in Powershell and press enter: `Get-Service -Name ssh-agent | Set-Service -StartupType Manual`

(This enables the ssh service again so that git can make sure it is you when you try to push or pull)
If you get different output for step 2 and 3 then just reply here and we can figure it out...

Steps I followed from second link:

1. Run Powershell again (or just use the same window if you still have Powershell open)
2. Type and enter `start-ssh-agent`
3. You might have to enter a password that you set yourself. If you have trouble then the password might be nothing (then you just press enter)
4. In Powershell, type and enter `code` then Visual Studio Code should start up. Then just open your repo and push/pull should work again

**Comment by CarlosTheran** [comment]
Great!!! thank you JP.
